imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
     handlers:
        out:
            ident: %app_name%
            type: error_log
            level: debug
            channels: ["!request", "!event", "!doctrine"]
            bubble: true
        storage_api:
            type: service
            id: app_bundle.event_handler
            ident: %app_name%
            level: info
            channels: ["!request", "!event", "!doctrine"]

assetic:
    use_controller: true
